/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 * Muestra al cliente las reservas relacionadas con él.
 * Muestra las reservas realizadas de un particular o las reservas realizadas a los inmuebles de un anfitrión
 * @author luver
 */

import clases.Datos;
import clases.Anfitrión;
import clases.Cliente;
import clases.Inmueble;
import clases.Reserva;
import java.util.ArrayList;

public class ConsultaReservas_Cliente extends javax.swing.JFrame {

    String tipo;
    PanelAnfitrion mainA;
    PanelParticular mainB;
    Anfitrión anfitrion;
    Cliente cliente;
    ArrayList<Reserva> reservasSelecc = new ArrayList<>();
    
    /**
     * Crea e inicializa la ventana con este constructor en caso de que el cliente sea un anfitrión
     * @param pa Ventana de origen
     * @param a Anfitrión de la sesión
     */
    public ConsultaReservas_Cliente(PanelAnfitrion pa, Anfitrión a) {
        initComponents();
        tipo = "A";
        mainA = pa;
        anfitrion = a;
        mainA.setVisible(false);
        for (int i = 0;i < Datos.lista_reservas.size();i++) {
            Reserva r = Datos.lista_reservas.get(i);
            int numerico = 0;
            for (int j = 0;j < Datos.lista_inmuebles.size();j++) {
                if (Datos.lista_inmuebles.get(j).getTitulo().equals(r.getTituloInmueble())
                        && Datos.lista_inmuebles.get(j).getDueño().equals(anfitrion.getNombre())) {
                    numerico = j;
                }
            }
            Inmueble in = Datos.lista_inmuebles.get(numerico);
            Cliente c = Datos.lista_clientes.get(r.getEmailCliente());
            this.jTable1.setValueAt(r.getTituloInmueble(), i, 0);//titulo inmueble
            this.jTable1.setValueAt(in.getTipoPropiedad(), i, 1);//tipo
            this.jTable1.setValueAt(in.getDireccion().getCalle()+", "+in.getDireccion().getNumero()+" - C.P.: "+in.getDireccion().getCodigoPostal(), i, 2);//direccion
            this.jTable1.setValueAt(in.getDireccion().getCiudad(), i, 3);//ciudad
            this.jTable1.setValueAt(in.getDueño(), i, 4);//anfitrion
            this.jTable1.setValueAt(c.getNombre(), i, 5);//particular
            this.jTable1.setValueAt(r.getEntrada(), i, 6);//fecha entrada
            this.jTable1.setValueAt(r.getSalida(), i, 7);//fecha salida
            this.jTable1.setValueAt(r.getImporte(), i, 8);//importe
        }
        this.setVisible(true);

    }
    
    /**
     * Crea e inicializa la ventana con este constructor en caso de que el cliente sea un particular
     * @param pp Ventana de origen
     * @param cl Cliente de la sesión
     */
    public ConsultaReservas_Cliente(PanelParticular pp, Cliente cl) {
        initComponents();
        tipo = "B";
        mainB = pp;
        cliente = cl;
        for (int i = 0;i < Datos.lista_reservas.size();i++) {
            Reserva r = Datos.lista_reservas.get(i);
            int numerico = 0;
            for (int j = 0;j < Datos.lista_inmuebles.size();j++) {
                if (Datos.lista_inmuebles.get(j).getTitulo().equals(r.getTituloInmueble())
                        && r.getEmailCliente().equals(cl.getEmail())) {
                    numerico = j;
                }
            }
            Inmueble in = Datos.lista_inmuebles.get(numerico);
            Cliente c = Datos.lista_clientes.get(r.getEmailCliente());
            this.jTable1.setValueAt(r.getTituloInmueble(), i, 0);//titulo inmueble
            this.jTable1.setValueAt(in.getTipoPropiedad(), i, 1);//tipo
            this.jTable1.setValueAt(in.getDireccion().getCalle()+", "+in.getDireccion().getNumero()+" - C.P.: "+in.getDireccion().getCodigoPostal(), i, 2);//direccion
            this.jTable1.setValueAt(in.getDireccion().getCiudad(), i, 3);//ciudad
            this.jTable1.setValueAt(in.getDueño(), i, 4);//anfitrion
            this.jTable1.setValueAt(c.getNombre(), i, 5);//particular
            this.jTable1.setValueAt(r.getEntrada(), i, 6);//fecha entrada
            this.jTable1.setValueAt(r.getSalida(), i, 7);//fecha salida
            this.jTable1.setValueAt(r.getImporte(), i, 8);//importe
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("C059", 0, 36)); // NOI18N
        jLabel1.setText("JavaBnB");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 2, 18)); // NOI18N
        jLabel2.setText("Consulta de reservas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Inmueble", "Tipo", "Dirección", "Ciudad", "Anfitrión", "Particular", "Fecha de entrada", "Fecha de salida", "Importe total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jButton1.setText("Volver al panel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Te lleva de vuelta a la ventana anterior
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tipo.equals("A")) {
            this.mainA.setVisible(true);
            this.setVisible(false);
        } else if (tipo.equals("B")) {
            this.mainB.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
